### ISSUE TITLE
Missing PubSub connect

### ISSUE THREAD

**Issue by toddtreece** [openhomeautomation/adafruit-io-dashboard#1]
This example seems to be missing the call to tell the pubsub client to connect to Adafruit IO's MQTT broker.

**Comment by marcoschwartz** [comment]
That's fixed now. Let me know if it works for you and I'll close the issue :)

**Comment by toddtreece** [comment]
@marcoschwartz I think you missed a rename. In the Adafruit IO basics code `client` is an instance of PubSubClient. It looks like you caught that it needed to be renamed in `mqtt_connect()`, but you missed the rename in the loop addition:

```
if(! client.connected())
```

`client` should be changed to `mqttclient` in your code so it's checking the MQTT connection status instead of the CC3k's: 

```
if(! mqttclient.connected())
```

`#define ADAFRUIT_USERNAME` could also be dropped since usernames aren't used in the Adafruit IO API.

I can't fully test this code because I don't have the DHT sensor, but it would probably be worth letting a test run on your hardware for a few hours to make sure it stays connected to Adafruit IO. Feel free to close if that seems stable to you. Thanks for the fixes!

**Comment by marcoschwartz** [comment]
You're right, just changed that. I'll test it on my own hardware and close this later.
